In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


# What Is A Tensor?
Simply put, a tensor is a collection of values. It can be a single value, one-dimensional, or multi-dimensional. 
![Visual Diagram of Tensor](https://miro.medium.com/max/700/0*jGB1CGQ9HdeUwlgB)
In mathematical terms, an $n^{th}$-rank tensor in $m$-dimensional space has $n$ indices and $m^n$ components. The image above may suggest that rank and dimensionality are the same. Mathematically-speaking, they are not. But for our purposes, we can think of them as the same thing.

In Tensorflow, all tensors have a uniform type or `dtype` (a list of `dtype`s can be found [here](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType)). Let's first create a "scalar" or "rank-0" tensor:

In [2]:
# A rank-0 tensor
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


As you can see, the tensor value is displayed as the first parameter and the `int32` as the last parameter. Notice, however, that the second parameter `shape` is empty. We will go over the `shape` parameter shortly.

Let's implement a rank-1 tensor (or a vector):

In [3]:
# A rank-1 tensor
rank_1_tensor = tf.constant([3.14, 1.592, 6, -5])
print(rank_1_tensor)

tf.Tensor([ 3.14   1.592  6.    -5.   ], shape=(4,), dtype=float32)


This is are pretty self-explanatory from the rank-0 tensor. Notice that the `dtype` is now a `float32` because we specified some floating-point values. 

Here's a rank-2 tensor (or matrix):

In [4]:
# A rank-2 tensor
rank_2_tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(rank_2_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


And here's a rank-4 tensor:

In [5]:
# A rank-4 tensor
rank_4_tensor = tf.constant([
    [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[1, 2], [3, 4]], [[5, 6], [7, 8]]],
    [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[1, 2], [3, 4]], [[5, 6], [7, 8]]],
    [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
])

Now that we have a few tensors under our belt, let's take a look at the `shape` variable:

In [6]:
print("Rank-0: ", rank_0_tensor.shape)
print("Rank-1: ", rank_1_tensor.shape)
print("Rank-2: ", rank_2_tensor.shape)
print("Rank-4: ", rank_4_tensor.shape)

Rank-0:  ()
Rank-1:  (4,)
Rank-2:  (3, 3)
Rank-4:  (9, 2, 2, 2)


The `shape` tuple can tell us a lot about the structure of a tensor. It's elements tell us about the length of a particular axis in the tensor. Notice that the length of the tuple tells us the rank of the tensor.

# Tensorflow Basics
Now that we understand the basics of a tensor, let's do some simple computations.

## Simple calculations

In [7]:
a = tf.constant([
    [1, 2],
    [3, 4]
])

b = tf.constant([
    [5, 6],
    [7, 8]
])

# Element-wise addition
add = tf.add(a, b)

# Element-wise multiplication
multiply = tf.multiply(a, b)

# Matrix multiplication
matmul = tf.matmul(a, b)

print(add, '\n')
print(multiply, '\n')
print(matmul, '\n')

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 



Operators like `+`, `-`, and `*` have been overriden in Tensorflow to make computations look a little more succinct.

In [8]:
print(a + b, '\n')
print(a - b, '\n')
print(a * b, '\n')

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 



Here are a few more overriden operators. Can you guess what they do?

In [9]:
print(a ** 5, '\n')
print(a @ b, '\n')

tf.Tensor(
[[   1   32]
 [ 243 1024]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 



## Initialization

We can also initialize tensors in different ways using `tf.ones`, `tf.zeros`, and `tf.eye`.

In [10]:
# A matrix full of 1s
ones = tf.ones((3, 3))

# A matrix full of 0s
zeros = tf.zeros((2, 4))

# An identity matrix
eye = tf.eye(3)

print(ones, '\n')
print(zeros, '\n')
print(eye, '\n')

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32) 

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(2, 4), dtype=float32) 

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32) 



Here are also a few randomly generated tensors:

In [11]:
# Tensor with values of a normal distribution
normal = tf.random.normal((3, 3), mean=0, stddev=1)

# Tensor with values of a Poisson distribution
poisson = tf.random.poisson(
    shape=(3, 2),
    lam=[3.14, 15.92, 65.35]
)

# Tensor with values of a Gamma distribution
gamma = tf.random.gamma(
    shape=(3, 4),
    alpha=[1.11, 2.22, 3.33]
)

print(normal, '\n')
print(poisson, '\n')
print(gamma, '\n')

tf.Tensor(
[[ 0.06072164 -0.69348675  0.6977107 ]
 [ 0.8282165  -1.4546869  -0.7995216 ]
 [ 1.7773803   1.4272352   1.4893292 ]], shape=(3, 3), dtype=float32) 

tf.Tensor(
[[[ 3. 23. 79.]
  [ 5. 24. 68.]]

 [[ 5. 11. 63.]
  [ 2. 12. 58.]]

 [[ 6. 16. 64.]
  [ 3. 14. 64.]]], shape=(3, 2, 3), dtype=float32) 

tf.Tensor(
[[[4.0439650e-02 1.6006520e+00 3.9261093e+00]
  [3.0370793e-01 1.7312568e+00 3.5833294e+00]
  [2.9998809e-01 2.4647996e+00 1.2586108e+00]
  [2.3612045e-01 8.3665234e-01 2.6893842e+00]]

 [[4.5333186e-01 2.2772911e+00 8.5172329e+00]
  [1.6875120e-03 6.6614830e-01 2.7921131e+00]
  [5.6562078e-01 1.5632170e+00 4.2659278e+00]
  [3.1484112e-01 1.0792449e+00 3.6364675e+00]]

 [[9.7452855e-01 5.9072089e-01 3.2466924e+00]
  [5.3994876e-01 1.0063773e+00 1.7456955e+00]
  [3.9032882e-01 2.5593288e+00 3.2262855e+00]
  [1.6132869e+00 7.8156400e-01 5.3831863e+00]]], shape=(3, 4, 3), dtype=float32) 



These are only a few of many ways to initialize a tensor with Tensorflow.

## Indexing

Tensorflow follows standard Python array indexing, as you'd expect:

In [12]:
a = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(a[0], '\n')
print(a[1], '\n')
print(a[2], '\n')

tf.Tensor([1 2 3], shape=(3,), dtype=int32) 

tf.Tensor([4 5 6], shape=(3,), dtype=int32) 

tf.Tensor([7 8 9], shape=(3,), dtype=int32) 



Notice that indexing a rank-2 tensor like this returns a rank-1 tensor. We can get the last tensor by negative indexing as well:

In [13]:
print(a[-1])

tf.Tensor([7 8 9], shape=(3,), dtype=int32)


We can get slices of a tensor with a colon `:`:

In [14]:
a = tf.constant([0, 1, 2, 3, 4, 5, 6, 7, 8])
print("All elements:", a[:].numpy())
print("Before third element:", a[:3].numpy())
print("From fourth element to end:", a[4:].numpy())
print("Elements between 4 and 7 (inclusive, exclusive):", a[4:7].numpy())
print("Reversed:", a[::-1].numpy())

All elements: [0 1 2 3 4 5 6 7 8]
Before third element: [0 1 2]
From fourth element to end: [4 5 6 7 8]
Elements between 4 and 7 (inclusive, exclusive): [4 5 6]
Reversed: [8 7 6 5 4 3 2 1 0]


Now let's try to index the following rank-3 tensor:

In [15]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]], 
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]]
])

Here's an image to help visualize this tensor:
![image of rank-3 tensor](https://www.tensorflow.org/guide/images/tensor/index1.png)

Indexing multi-axial tensors works the same way as indexing a single-axis one. Here we're going to extract each 'layer' of the tensor:

In [16]:
# Indexing by layer
print("First layer:\n",  rank_3_tensor[0, :].numpy(), '\n')
print("Second layer:\n", rank_3_tensor[1, :].numpy(), '\n')
print("Third layer:\n",  rank_3_tensor[2, :].numpy(), '\n')

First layer:
 [[0 1 2 3 4]
 [5 6 7 8 9]] 

Second layer:
 [[10 11 12 13 14]
 [15 16 17 18 19]] 

Third layer:
 [[20 21 22 23 24]
 [25 26 27 28 29]] 



Now let's try to extract the last column of each layer.

In [17]:
# Getting the last column of each layer
print("Last column of first layer:\n",  rank_3_tensor[0, :, -1].numpy(), '\n')
print("Last column of second layer:\n", rank_3_tensor[1, :, -1].numpy(), '\n')
print("Last column of third layer:\n",  rank_3_tensor[2, :, -1].numpy(), '\n')

Last column of first layer:
 [4 9] 

Last column of second layer:
 [14 19] 

Last column of third layer:
 [24 29] 



Lastly, let's try to index the bottom center value of every layer in a single call.

In [18]:
# Bottom center value of every layer
print(rank_3_tensor[:, 1, 2].numpy())

[ 7 17 27]


## Reshaping

We understand the basics of tensor shapes. Let's learn how to manipulate them.

Here, we have a rank-1 tensor:

In [19]:
rank_1_tensor = tf.range(0, 18)
print(rank_1_tensor)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17], shape=(18,), dtype=int32)


We can reshape this into a rank-2 tensor or a rank-3 tensor:

In [20]:
# Reshaping into a rank-2 tensor
rank_2_tensor = tf.reshape(rank_1_tensor, (9, 2))
rank_3_tensor = tf.reshape(rank_1_tensor, (2, 3, 3))

print("Rank-2 Tensor:\n", rank_2_tensor, '\n')
print("Rank-3 Tensor:\n", rank_3_tensor, '\n')

Rank-2 Tensor:
 tf.Tensor(
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]], shape=(9, 2), dtype=int32) 

Rank-3 Tensor:
 tf.Tensor(
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]], shape=(2, 3, 3), dtype=int32) 

